과제제출
Altu-Bitu/Altu-Bitu-study pull request #10
Opened 2021-09-30 02:58 UTC by yewonbahn

다못풀었는데 자정내로 추가되는부분 추가로제출하겟습니다!ㅜ

2021-09-30 05:01 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 지금 그럼 2문제 제출하시고, 1문제만 맞으신거네요!
근데 일단 두 문제 다 수정할 곳이 있어요
수정 후 리뷰어로 저 호출해주세요~
하시다가 모르겠는 부분은 물어봐주세요

2021-09-30 05:01 UTC, HyunJiLim0406 commented on 0924 - backtracking/15665.cpp
> +            continue;
p1
저희가 check 배열을 쓸 때는 check 배열을 어떻게 다뤘었나요?
check를 true로 해서 방문을 표시한 후, 백트래킹 함수를 호출하고 방문 표시를 지우기 위해 check를 false로 바꿔주었어요
이 코드에는 check 배열을 조작하는 부분 자체가 없어서 !check가 항상 true네요~
else-continue도 필요없어지겠어요!
좀만 수정해볼까요?
힌트는 이 코드가 맞았습니다를 받았다는 '사실'이에요

2021-09-30 05:01 UTC, HyunJiLim0406 commented on 0924 - backtracking/1759.cpp
> +int main(){
p1
이 코드는 맞았습니다를 못받으셨을 것 같네요
일단 저희는 유효한 암호를 '사전순'으로 출력해야하구요
모음 2개 이상, 자음 1개 이상이라는 조건을 충족해야해요

힌트를 드리자면 두번째 조건은 기저조건에서 확인하면 돼요

2021-10-05 01:17 UTC, JiyooonPark reviewed
필수 과제 1개 + 선택과제 1개 확인되셨습니다. 머지해주세요!

2021-10-05 12:29 UTC, merged